name: femi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.1.2
  calendar_slider: ^0.0.4
  animations: ^2.0.11
  google_fonts: ^6.2.1
  lottie: ^3.1.3
  linear_progress_bar: ^1.1.2
  stylish_bottom_bar: ^1.1.0
  curved_labeled_navigation_bar: ^2.0.5
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  sqflite: ^2.3.3+1
  path: ^1.9.0
  intl: ^0.19.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  firebase_messaging: ^15.1.5
  http: ^1.2.2
  google_sign_in: ^6.2.2
  sign_in_button: ^3.2.0
  foundation: ^0.0.5
  convex_bottom_bar: ^3.2.0
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/home/
    - assets/Insights/
    - assets/setting/
    - assets/images/
    - assets/logsymptom/
    - assets/animation/animation1.json
    - assets/animation/circle1.json
    - assets/animation/login.json
    - assets/animation/circle2.json
    - assets/animation/girly.json
    - assets/animation/hey.json
    - assets/animation/message.json
    - assets/animation/partner.json
    - assets/animation/pregnancy.json
    - assets/periodchat/
    - assets/pregpage/
